# Generated by Django 4.1.2 on 2023-06-05 00:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_canceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('canceler', models.CharField(choices=[('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('time_cancel', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('receiver', models.CharField(blank=True, default='doc,', max_length=20, null=True)),
                ('sender', models.CharField(blank=True, default='ptn,', max_length=20, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_notice', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site_admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount_transact', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('appoint_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('waiting', 'Đang chờ'), ('pending', 'Đang chờ xác nhận'), ('denied', 'Đã từ chối'), ('appointing', 'Đang khám')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_transaction', models.IntegerField(default=1)),
                ('appoint_address', models.TextField(default='')),
                ('creator', models.CharField(choices=[('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân'), ('admin', 'Admin'), ('system', 'Hệ thống')], default='doctor', max_length=20)),
                ('canceled_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admins.detail_canceled')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('medical_specialty', models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount_transact', models.IntegerField()),
                ('appoint_time', models.DateTimeField()),
                ('appoint_address', models.TextField(default='')),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_transaction', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('refund', 'Hoàn tiền')], default='success', max_length=20)),
                ('show_on_doctor', models.BooleanField(default=True)),
                ('show_on_patient', models.BooleanField(default=True)),
                ('show_on_admin', models.BooleanField(default=True)),
                ('canceled_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admins.detail_canceled')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('medical_specialty', models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
