# Generated by Django 4.1.7 on 2023-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='CCCD',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
