# Generated by Django 4.1.7 on 2023-06-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='XA',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
