# Generated by Django 4.1.7 on 2023-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0002_transaction_cccd'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sotinh',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
