# Generated by Django 4.1.7 on 2023-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0003_transaction_sotinh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='CCCD',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sotinh',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='birth_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
