# Generated by Django 4.1.7 on 2023-06-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0004_remove_transaction_cccd_remove_transaction_sotinh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='country',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='district',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reason',
        ),
    ]
