# Generated by Django 4.1.7 on 2023-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_time_per_appoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='avatar',
            field=models.FileField(default='/media/images/default.jpeg', max_length=255, upload_to='D:\\Tài liệu Kỳ 4\\CTDL\\webdatlich1\\mysite\\media\\images'),
        ),
    ]
