# Generated by Django 4.1.2 on 2023-04-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
