# Generated by Django 4.1.2 on 2023-03-20 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default=None, upload_to='media'),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_identification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_choice',
            field=models.CharField(choices=[('MN', 'Men'), ('WM', 'Phu nu'), ('TH', 'Khong xac dinh')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_join',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
