# Generated by Django 4.1.2 on 2023-03-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender_choice',
            field=models.CharField(choices=[('MN', 'Nam'), ('WM', 'Nữ'), ('TH', 'Không xác định')], default='TH', max_length=2),
        ),
    ]
