# Generated by Django 4.1.2 on 2023-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_address_remove_user_gender_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizen_identification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
