# Generated by Django 4.1.2 on 2023-04-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_citizen_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citizen_identification',
        ),
    ]
