# Generated by Django 4.1.2 on 2023-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_citizen_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen_identification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
