# Generated by Django 4.1.2 on 2023-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Tên'),
        ),
    ]
