# Generated by Django 4.1.2 on 2023-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Nam'), ('woman', 'Phu nu'), ('undefined', 'Khong xac dinh')], default='undefined', max_length=20),
        ),
    ]
