# Generated by Django 4.1.2 on 2023-04-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_a',
            field=models.IntegerField(null=True),
        ),
    ]
