# Generated by Django 4.1.2 on 2023-04-02 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_new_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='new_a',
            new_name='new_age',
        ),
    ]
