# Generated by Django 4.1.2 on 2023-04-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_new_a_user_new_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
