# Generated by Django 4.1.2 on 2023-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_new_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('man', 'Nam'), ('woman', 'Nữ'), ('undefined', 'Không xác định')], default='undefined', max_length=20),
        ),
    ]
