# Generated by Django 4.1.2 on 2023-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='D:\\C++_workspace\\projects\\helloworld\\Web_book_appointment_with_doctor_1\\mysite\\media\\default.jpg', upload_to='avatar'),
        ),
    ]
