# Generated by Django 4.1.2 on 2023-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/media/images/default.jpeg', max_length=255, upload_to='D:\\C++_workspace\\projects\\helloworld\\Web_book_appointment_with_doctor_1\\mysite\\media\\images'),
        ),
    ]
