# Generated by Django 4.1.2 on 2023-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_join',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
