# Generated by Django 4.1.2 on 2023-06-05 00:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.IntegerField(default=0)),
                ('money_left', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('is_auth', models.BooleanField(default=False)),
                ('available_time', models.TextField(default='[]')),
                ('time_per_appoint', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('name', models.CharField(choices=[('nha_khoa', 'Nha khoa'), ('tim_mach', 'Tim mạch'), ('da_lieu', 'Da liễu'), ('mat', 'Mắt'), ('xuong_khop', 'Xương khớp')], default='nha_khoa', max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('avatar', models.FileField(default='/media/images/default.jpeg', max_length=255, upload_to='D:\\C++_workspace\\projects\\helloworld\\Web_book_appointment_with_doctor_1\\mysite\\media\\images')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('feedback', models.TextField()),
                ('time_feedback', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('sender_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MyPaient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('counter', models.IntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties'),
        ),
    ]
