# Generated by Django 4.1.2 on 2023-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nha_khoa', 'Nha khoa (răng hàm mặt)'), ('tim_mach', 'Tim mạch'), ('da_lieu', 'Da liễu'), ('mat', 'Mắt'), ('xuong_khop', 'Xương khớp')], max_length=255)),
                ('description', models.TextField()),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
