# Generated by Django 4.1.2 on 2023-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
