# Generated by Django 4.1.2 on 2023-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='name',
            field=models.CharField(choices=[('xuong_khop', 'Xương khớp'), ('than_kinh', 'Thần Kinh'), ('tieu_hoa', 'Tiêu Hóa'), ('tim_mach', 'Tim mạch'), ('tai_mui_hong', 'Tai Mũi Họng'), ('cot_song', 'Cột Sống'), ('da_lieu', 'Da Liễu'), ('ho_hap_phoi', 'Hô Hấp - Phổi'), ('nha_khoa', 'Nha khoa')], default='nha_khoa', max_length=255, primary_key=True, serialize=False),
        ),
    ]
