# Generated by Django 4.1.2 on 2023-04-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialties',
            name='name',
        ),
    ]
