# Generated by Django 4.1.2 on 2023-04-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_specialties_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialties',
            name='name',
            field=models.CharField(choices=[('nha_khoa', 'Nha khoa (răng hàm mặt)'), ('tim_mach', 'Tim mạch'), ('da_lieu', 'Da liễu'), ('mat', 'Mắt'), ('xuong_khop', 'Xương khớp')], max_length=255, null=True),
        ),
    ]
