# Generated by Django 4.1.2 on 2023-06-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_specialties_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.TextField(default='[{"day":1,"time":[]},{"day":2,"time":[]},{"day":3,"time":[]},{"day":4,"time":[]},{"day":5,"time":[]}{"day":6,"time":[]},{"day":7,"time":[]}]'),
        ),
    ]
