# Generated by Django 4.1.2 on 2023-06-05 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_is_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='time_per_appoint',
        ),
    ]
