# Generated by Django 4.1.2 on 2023-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_time_per_appoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='time_per_appoint',
            field=models.IntegerField(default=30),
        ),
    ]
