# Generated by Django 4.1.2 on 2023-06-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time_per_appoint',
            field=models.IntegerField(null=True),
        ),
    ]
