# Generated by Django 4.1.2 on 2023-04-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_specialties_id_alter_specialties_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='name',
            field=models.CharField(choices=[('nha_khoa', 'Nha khoa'), ('tim_mach', 'Tim mạch'), ('da_lieu', 'Da liễu'), ('mat', 'Mắt'), ('xuong_khop', 'Xương khớp')], default='nha_khoa', max_length=255, primary_key=True, serialize=False),
        ),
    ]
