# Generated by Django 4.1.2 on 2023-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_time_per_appoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time_per_appoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
