# Generated by Django 4.1.2 on 2023-05-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
