# Generated by Django 4.1.2 on 2023-06-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctor_bookable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bookable_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
