# Generated by Django 4.1.2 on 2023-05-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctor_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialties',
            old_name='picture',
            new_name='avatar',
        ),
    ]
