# Generated by Django 4.1.2 on 2023-05-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_doctor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='money_left',
            field=models.IntegerField(default=0),
        ),
    ]
