# Generated by Django 4.1.2 on 2023-05-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_money_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('feedback', models.TextField()),
                ('time_feedback', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='doctors.review'),
        ),
    ]
