# Generated by Django 4.1.2 on 2023-05-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_age'),
        ('doctors', '0014_review_alter_doctor_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id_send',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
