# Generated by Django 4.1.2 on 2023-05-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_review_id_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.review'),
        ),
    ]
