# Generated by Django 4.1.2 on 2023-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_alter_doctor_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
