# Generated by Django 4.1.2 on 2023-05-17 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_age'),
        ('doctors', '0017_alter_doctor_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rate',
        ),
        migrations.AddField(
            model_name='review',
            name='receiver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_send',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
