# Generated by Django 4.1.2 on 2023-05-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_remove_doctor_rate_review_receiver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='receiver_id',
        ),
    ]
