# Generated by Django 4.1.2 on 2023-05-17 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_remove_review_receiver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='receiver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
