# Generated by Django 4.1.2 on 2023-05-17 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_review_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='receiver_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
