# Generated by Django 4.1.2 on 2023-05-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0022_remove_doctor_income_alter_review_receiver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
