# Generated by Django 4.1.2 on 2023-05-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_doctor_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='avatar',
            field=models.FileField(default='/media/images/default.jpeg', max_length=255, upload_to='D:\\C++_workspace\\projects\\helloworld\\Web_book_appointment_with_doctor_1\\mysite\\media\\images'),
        ),
    ]
