# Generated by Django 4.1.2 on 2023-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0025_mypaient'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypaient',
            name='counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mypaient',
            name='last_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
