# Generated by Django 4.1.2 on 2023-05-18 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0026_mypaient_counter_mypaient_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypaient',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 16, 56, 57, 562955), null=True),
        ),
    ]
