# Generated by Django 4.1.2 on 2023-05-19 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_age'),
        ('doctors', '0027_alter_mypaient_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypaient',
            name='last_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 20, 29, 31, 355091), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_send',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
