# Generated by Django 4.1.2 on 2023-05-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0029_alter_mypaient_last_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='id_send',
            new_name='sender_id',
        ),
    ]
