# Generated by Django 4.1.2 on 2023-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0030_rename_id_send_review_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
