# Generated by Django 4.2 on 2023-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0030_rename_id_send_review_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialties',
            name='avatar',
            field=models.FileField(default='/media/images/default.jpeg', max_length=255, upload_to='E:\\tai_lieu_o_truong\\CauTrucDuLieu\\khach\\Web_project_store-patient\\mysite\\media\\images'),
        ),
    ]
