# Generated by Django 4.1.2 on 2023-06-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0031_doctor_is_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.TextField(default='[]'),
        ),
    ]
