# Generated by Django 4.1.2 on 2023-06-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_canceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('canceler', models.CharField(choices=[('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('time_cancel', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount_transact', models.IntegerField()),
                ('appoint_time', models.DateTimeField()),
                ('appoint_address', models.TextField(default='')),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_transaction', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('refund', 'Hoàn tiền')], default='success', max_length=20)),
                ('show_on_doctor', models.BooleanField(default=True)),
                ('show_on_patient', models.BooleanField(default=True)),
                ('show_on_admin', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('receiver', models.CharField(blank=True, default='doc,', max_length=20, null=True)),
                ('sender', models.CharField(blank=True, default='ptn,', max_length=20, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_notice', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
