# Generated by Django 4.1.2 on 2023-06-08 03:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('users', '0001_initial'),
        ('doctors', '0001_initial'),
        ('site_admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount_transact', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('appoint_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('waiting', 'Đang chờ'), ('pending', 'Đang chờ xác nhận'), ('denied', 'Đã từ chối'), ('appointing', 'Đang khám')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_transaction', models.IntegerField(default=1)),
                ('appoint_address', models.TextField(default='')),
                ('creator', models.CharField(choices=[('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân'), ('admin', 'Admin'), ('system', 'Hệ thống')], default='doctor', max_length=20)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('canceled_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admins.detail_canceled')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('medical_specialty', models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='canceled_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admins.detail_canceled'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='medical_specialty',
            field=models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
