# Generated by Django 4.1.2 on 2023-04-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0003_remove_patient_age'),
        ('site_admins', '0002_finance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finance',
            new_name='Transaction',
        ),
    ]
