# Generated by Django 4.1.2 on 2023-06-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='country',
            new_name='info_patient',
        ),
    ]
