# Generated by Django 4.1.2 on 2023-06-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0003_rename_country_transaction_info_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='info_patient',
            field=models.TextField(blank=True, null=True),
        ),
    ]
