# Generated by Django 4.1.2 on 2023-04-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0003_rename_finance_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('confirming', 'Đang chờ')], default='confirming', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
