# Generated by Django 4.1.2 on 2023-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0004_transaction_state_alter_transaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='medical_specialties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
