# Generated by Django 4.1.2 on 2023-06-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0005_transaction_citizen_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
