# Generated by Django 4.1.2 on 2023-04-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0005_alter_transaction_medical_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='medical_specialties',
        ),
        migrations.AddField(
            model_name='transaction',
            name='medical_specialtie',
            field=models.TextField(blank=True, choices=[('nha_khoa', 'Nha khoa (răng hàm mặt)'), ('tim_mach', 'Tim mạch'), ('da_lieu', 'Da liễu'), ('mat', 'Mắt'), ('xuong_khop', 'Xương khớp')], null=True),
        ),
    ]
