# Generated by Django 4.1.2 on 2023-04-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0006_remove_transaction_medical_specialties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='medical_specialtie',
            new_name='medical_speciality',
        ),
    ]
