# Generated by Django 4.1.2 on 2023-06-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0006_notification_title_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='citizen_identification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
