# Generated by Django 4.1.2 on 2023-04-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialties'),
        ('site_admins', '0007_rename_medical_specialtie_transaction_medical_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='medical_speciality',
        ),
        migrations.AddField(
            model_name='transaction',
            name='medical_specialty',
            field=models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties'),
            preserve_default=False,
        ),
    ]
