# Generated by Django 4.1.2 on 2023-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0008_remove_transaction_medical_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='medical_specialty',
        ),
    ]
