# Generated by Django 4.1.2 on 2023-04-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_specialties_id_alter_specialties_name'),
        ('site_admins', '0009_remove_transaction_medical_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='medical_specialty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties'),
            preserve_default=False,
        ),
    ]
