# Generated by Django 4.1.2 on 2023-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0012_transaction_id_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
    ]
