# Generated by Django 4.1.2 on 2023-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0013_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spec',
            field=models.CharField(choices=[('nha_khoa', 'Nha khoa'), ('tim_mach', 'Tim mạch'), ('da_lieu', 'Da liễu'), ('mat', 'Mắt'), ('xuong_khop', 'Xương khớp')], default='nha_khoa', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('waiting', 'Đang chờ')], max_length=20),
        ),
    ]
