# Generated by Django 4.1.2 on 2023-04-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0015_alter_transaction_medical_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spec',
            new_name='specialties',
        ),
    ]
