# Generated by Django 4.1.2 on 2023-04-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_specialties_name'),
        ('site_admins', '0016_rename_spec_transaction_specialties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='specialties',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='medical_specialty',
            field=models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties'),
        ),
    ]
