# Generated by Django 4.1.2 on 2023-04-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0017_remove_transaction_specialties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_canceled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('canceler', models.CharField(choices=[('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('time_cancel', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
