# Generated by Django 4.1.2 on 2023-04-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0018_detail_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='canceled_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admins.detail_canceled'),
        ),
    ]
