# Generated by Django 4.1.2 on 2023-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0019_transaction_canceled_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_canceled',
            name='id_transaction',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
