# Generated by Django 4.1.2 on 2023-04-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0020_detail_canceled_id_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
