# Generated by Django 4.1.2 on 2023-05-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0022_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notice',
            new_name='content',
        ),
    ]
