# Generated by Django 4.1.2 on 2023-05-16 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_money_left'),
        ('patients', '0003_remove_patient_age'),
        ('site_admins', '0023_rename_notice_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('waiting', 'Đang chờ'), ('pending', 'Đang chờ xác nhận')], max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount_transact', models.IntegerField()),
                ('appoint_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_transaction', models.IntegerField(default=1)),
                ('canceled_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_admins.detail_canceled')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('medical_specialty', models.ForeignKey(default='nha_khoa', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialties')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('content', models.TextField()),
                ('time_feedback', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
