# Generated by Django 4.1.2 on 2023-05-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctor_money_left'),
        ('patients', '0003_remove_patient_age'),
        ('site_admins', '0025_alter_feedback_receiver_id_alter_feedback_sender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('content', models.TextField()),
                ('time_feedback', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
