# Generated by Django 4.1.2 on 2023-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0027_review_delete_rates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='feedback',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(),
        ),
    ]
