# Generated by Django 4.1.2 on 2023-05-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0028_rename_content_review_feedback_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='receiver_id',
        ),
    ]
