# Generated by Django 4.1.2 on 2023-05-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0029_remove_review_receiver_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
