# Generated by Django 4.1.2 on 2023-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0030_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='appoint_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
