# Generated by Django 4.1.2 on 2023-05-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0031_transaction_appoint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='appoint_address',
            field=models.TextField(default=''),
        ),
    ]
