# Generated by Django 4.1.2 on 2023-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0032_alter_transaction_appoint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='appoint_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
