# Generated by Django 4.1.2 on 2023-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0033_alter_transaction_appoint_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_on_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='show_on_doctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='show_on_patient',
            field=models.BooleanField(default=True),
        ),
    ]
