# Generated by Django 4.1.2 on 2023-05-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0034_invoice_show_on_admin_invoice_show_on_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='creator',
            field=models.CharField(default='doctor', max_length=20),
        ),
    ]
