# Generated by Django 4.1.2 on 2023-05-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0035_transaction_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appoint_address',
            field=models.TextField(default=''),
        ),
    ]
