# Generated by Django 4.1.2 on 2023-05-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0036_invoice_appoint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
