# Generated by Django 4.1.2 on 2023-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0037_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('success', 'Thành công'), ('refund', 'Hoàn tiền')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='creator',
            field=models.CharField(choices=[('doctor', 'Bác sĩ'), ('patient', 'Bệnh nhân'), ('admin', 'Admin'), ('system', 'Hệ thống')], default='doctor', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('waiting', 'Đang chờ'), ('pending', 'Đang chờ xác nhận'), ('denied', 'Đã từ chối')], max_length=20),
        ),
    ]
