# Generated by Django 4.1.2 on 2023-05-23 11:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0030_rename_id_send_review_sender_id'),
        ('patients', '0003_remove_patient_age'),
        ('site_admins', '0038_alter_invoice_status_alter_transaction_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='receiver_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='notification',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_notice',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
