# Generated by Django 4.1.2 on 2023-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0039_remove_notification_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_notice',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
