# Generated by Django 4.1.2 on 2023-05-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0040_alter_notification_time_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('success', 'Thành công'), ('failure', 'Thất bại'), ('waiting', 'Đang chờ'), ('pending', 'Đang chờ xác nhận'), ('denied', 'Đã từ chối'), ('appointing', 'Đang khám')], max_length=20),
        ),
    ]
