# Generated by Django 4.1.2 on 2023-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0041_alter_transaction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='appoint_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
