# Generated by Django 4.1.2 on 2023-05-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0042_alter_transaction_appoint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.CharField(default='doc,', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(default='ptn,', max_length=20, null=True),
        ),
    ]
