# Generated by Django 4.2 on 2023-05-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_admins', '0043_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.CharField(blank=True, default='doc,', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, default='ptn,', max_length=20, null=True),
        ),
    ]
