from django.contrib.auth.decorators import user_passes_test
from django.urls import path, include
from .views import (admin_login_view,
                    admin_home_view,
                    patient_manage_view,
                    dashboard,
                    new_patient_register_search_view,
                    new_doctor_register_search_view,
                    new_transaction_view,
                    new_appointment_view,
                    logout_account,
                    logout_page,
                    test_json,
                    appoints_total_data,
                    appoints_state_data,
                    specialities_table_data,
                    specialities_income_chart_data,
                    download_csv,
                    get_data_patient,
                    get_data_patients,
                    delete_patient,
                    update_patient_info,
                    add_patient,
                    get_name_list_chosen_item,
                    )
app_name = "site_admin"

urlpatterns = [
    path('login/', (admin_login_view), name = "login"),
    path('home/',  admin_home_view, name = "home"),
	path('patient-manage/', patient_manage_view, name = "patient"),
    path('dashboard/', dashboard, name = "dashboard"),
    path('get-new-data/', new_patient_register_search_view, name = "total_new_patient"),
    path('get-new-data-doctor/', new_doctor_register_search_view, name = "total_new_doctor"),
    path('get-new-data-transaction/', new_transaction_view, name = "total_new_transaction"),
    path('get-new-data-booking/', new_appointment_view, name = "total_new_appointment"),
    path('lg', logout_account, name = "logout_link"),
    path('logout/', logout_page, name = "logout_page"),
    # path('test_json/', test_json),
    path('appoints-state-data/', appoints_state_data),
    path('appoints-total/', appoints_total_data),
    path('specialities_table_data/', specialities_table_data),
    path('spec-income-chart-data/', specialities_income_chart_data),
    path('export-file/', download_csv),
    path('get-data-patient/', get_data_patient),
    path('get-data-patients/', get_data_patients),
    path('delete-patient/', delete_patient),
    path('update-patient-info/', update_patient_info),
    path('add-patient/', add_patient),
    path('get-name-list-chosen-item/', get_name_list_chosen_item)
]
